jobs:
  build-oke:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_PIPELINE }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PIPELINE }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Build APK with Python script
        run: |
          pip install --upgrade pip
          pip install setuptools
          python build_apk.py

      - name: Push APK to repository
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add build_output/*.apk
          git commit -m "🚀 Add built APK from pipeline"
          git push origin dev